// Service
const HOST = "127.0.0.1"
const PORT = 3000

// HMR
const HMR_URL = `http://${HOST}:${PORT}/__webpack_hmr`

// AUTO_RELOAD
const AUTO_RELOAD_EXTENSION_URL = "/auto_reload_extension"
const AUTO_RELOAD_URL = `http://${HOST}:${PORT}${AUTO_RELOAD_EXTENSION_URL}`

// SSE
const SSE_EVENT = {
  CONTENT_SCRIPT_COMPILED_SUCCESSFULLY: "CONTENT_SCRIPT_COMPILED_SUCCESSFULLY",
}
const SSE_ACTION = {
  RELOAD_EXTENSION_CONTENT_SCRIPT: "RELOAD_EXTENSION_CONTENT_SCRIPT",
}

// MESSAGE
const MESSAGE_FROM = {
  BACKGROUND: "BACKGROUND",
  CONTENT_SCRIPT: "CONTENT_SCRIPT",
}
const MESSAGE_ACTION = {
  RELOAD_CONTENT_SCRIPT: "RELOAD_CONTENT_SCRIPT",
  RELOAD_EXTENSION: "RELOAD_EXTENSION",
}

module.exports = {
  AUTO_RELOAD_EXTENSION_URL,
  AUTO_RELOAD_URL,
  HMR_URL,
  MESSAGE_ACTION,
  MESSAGE_FROM,
  PORT,
  SSE_ACTION,
  SSE_EVENT,
}
